public class GoalSeek_a {

    public String getProjectedrevenue() {
        return null;
    }

String targetrevenue;
String classtype;
String quarter;


public String getTargetrevenue(){
  return targetrevenue;
}
public void setTargetrevenue(String targetrevenue){
   this.targetrevenue = targetrevenue;
}

public String getClasstype(){
  return classtype;
}
public void setClasstype(String classtype){
   this.classtype= classtype;
}

public String getQuarter(){
  return quarter;
}
public void setQuarter(String quarter){
   this.quarter= quarter;
}

public PageReference estimate(){
 return null;
}

}