public class myClass1 {
String username;
String user;
String numb = '123';
Integer no;
public void setNumb(String s){
   this.numb = s;
   }
   public String getNumb(){
   return this.numb;
   }
   public Integer getno(){
       no = Integer.valueOf(numb);
       return this.no;
   }
 public String getxyz(){
   userName = myClass.getContextUserName();
   return userName;
    }
    public String getabc(){
    return user;
    }

}